#!/bin/bash

export DISPLAY=:0
export HOME=/config
export XDG_CONFIG_HOME=/config/.config
export XDG_DATA_HOME=/config/.local/share
export XDG_CACHE_HOME=/config/.cache
export XDG_RUNTIME_DIR=/tmp/runtime-root

mkdir -p /config/chromium

exec /usr/bin/chromium \
    --no-sandbox \
    --disable-dev-shm-usage \
    --disable-gpu \
    --user-data-dir=/config/chromium \
    "$@"